version: '3.1'

services:
  xampp:
    image: tomsik68/xampp:5
    container_name: xampp-server
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 22:22
    volumes:
      - ./xampp/www:/wwww
      - ./xampp/logs:/logs
      - ./xampp/mysql:/mysql
      - ./xampp/htdocs:/htdocs
      - ./xampp/tmp:/tmp
      - ./xampp/conf:/opt/lampp/apache2/conf.d
    restart: always

volumes:
  xampp:
    driver: local

configs:
  httpd-config:
    external: true